version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sha-rek-api
    command: sh -c "npx prisma generate && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://sharek:sharekSecurePass2026@postgres:5432/sharek_db
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=jlVa_hzqZ55_EJDahAdTBx_access_secret_key
      - JWT_REFRESH_SECRET=jlVa_hzqZ55_EJDahAdTBx_refresh_secret_key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sha-rek-network

  postgres:
    image: postgres:16-alpine
    container_name: sha-rek-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sharek
      - POSTGRES_PASSWORD=sharekSecurePass2026
      - POSTGRES_DB=sharek_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sharek -d sharek_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sha-rek-network

volumes:
  postgres_data:

networks:
  sha-rek-network:
    driver: bridge
